# stage1 - build react app first 
FROM node:14.15.4 as build
WORKDIR /my-react-app
ENV PATH /my-react-app/node_modules/.bin:$PATH
COPY ./package.json /my-react-app/
RUN yarn --silent
COPY . /my-react-app
RUN yarn build

# stage 2 - build the final image and copy the react build files
FROM nginx:1.17.8-alpine
COPY --from=build /my-react-app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/conf.d
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]